# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: UseDotNet@2
  displayName: 'Use .NET SDK 6.0'
  inputs:
    packageType: sdk
    version: 6.x
    performMultiLevelLookup: true
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    sourceScanPath: 'scenarios/telemetry/dotnet/telemetry_consumer'
    alertWarningLevel: 'High'
    
- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'High'

- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'Register'
    useDefaultDetectors: false
    detectorsToRun: 'NuGet'
    verbosity: 'Verbose'
    sourceScanPath: 'scenarios/telemetry/dotnet/telemetry_consumer'
    alertWarningLevel: 'High'