name: dotnet Checks

on:
  push:
    branches: [ "main" ]

  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Execute unit tests
        run: dotnet test scenarios/Scenarios.sln